services:
  api:
    build: .
    ports:
      - '8050:8050'
    environment:
      - DB_URL=sqlite:////data/items.db
    volumes:
      - items_data:/data
    restart: unless-stopped # arranca autom√°ticamente con el sistema
  
  web:
    image: nginx:latest
    container_name: nginx_service
    restart: always
    ports:
      - "8080:80"


volumes:
  items_data:
